### ISSUE TITLE
Import functions currently do not check for correct standard formatting

### ISSUE THREAD

**Issue by sophiamaedler** [bedapub/besca#12]
Currently there are no checks in place that ensure that the formatting of the input files matches our established standard. For example, if genes.tsv only contains one column with gene symbols this does not currently throw a warning or error but the user will encounter issues at later time points when trying to export results or use other functions in besca that are written to deal with adata formats in a specific format. 

The checks should be fairly simple to implement but the question is how we want to deal with the issue of users having slightly differently formatted datasets in general. Currently I think it would be good to do initial checks when ever a data object is loaded and give out warnings if the format does not comply with our standard format with basic information on what needs to be changed to fix the issues. This way the user still has the possibility to proceed with differently formatted datasets, but is aware that this may raise issues down the road. The documentation should also contain a section on the standard data format. What are other opinions on this?

**Comment by hatjek** [comment]
I agree. We should print warnings, but not blocking the workflow. We should also include some description of those file formats in the documentation and examples in the tutorials.

**Comment by ajulienla** [comment]
Hi,
Totally agrees, this goes with #6  but more clearly put. Our I/O standards are not explicit and should be to avoid discouraging users and fixing bugs that are formatting issue.

**Comment by Artemis-R** [comment]
@hatjek @ajulienla: Quick clarification on our standards. What do you do when only gene symbols are present but no ENSEMBL IDs. My first intuition was to simply put a column in genes.tsv which contains "NA". This leads to issues though since "NA" is automatically parsed to np.nan when using pd.read_csv. I can fix this issue by updating the import function but wanted to align first.

**Comment by ajulienla** [comment]
the same standard remained since you left.
the pd.read_csv problem would be for additional post-processing ? I think it is fine if adding a warning for the user.

**Comment by swalpe** [comment]
For the IDs we have so far removed all genes that don't have both symbols and ENSEMBL IDs

**Comment by ajulienla** [comment]
Some additional notes, I think we do need a  check-input function.

I encounter problem within the standard workflow incorporating some public data:

adata.X **should** be  sparse (can be fixed with sparce.csr_matrix(adata.X)) for the kp plot
ENSEMBL and SYMBOL columns  are **mandatory** for exporting. (mentionned by Sophia above).

**Comment by Artemis-R** [comment]
further requirements:
- adata.obs needs to contain 'CELL' which is equivalent to adata.obs_names

**Comment by Artemis-R** [comment]
Summary of checks needed to be performed:
- adata.obs needs to contain 'CELL' which is equivalent to adata.obs_names
- adata.var needs to contain both SYMBOL and ENSEMBL → best practice when one of the two is not present in public dataset replace column with string containing 'N.A.'? (@swalpe, @hatjek, @ajulienla )
- adata.X needs to be sparse

Also documentation needs to be updated to include an overview of our standard format.

**Comment by ajulienla** [comment]
Hi,
yes;  
additional check :
- adata.var: ENSEMBL and SYMBOL are **string** only. Otherwise ZIP is failing afterwards while writing information.

**Comment by kohleman** [comment]
@llumdi How could we check that an ID is a valid ENSEMBL ID?
Do you mean the stable IDs (https://www.ensembl.org/Help/Faq?id=488)?

**Comment by llumdi** [comment]
Let's discuss

**Comment by llumdi** [comment]
To clarify my comment:
A typical `genes.tsv` file have 3 columns with: ENS id, gene symbol, and 1 specifying the modality e.g: Gene Expression.
Example:

![Snag_7173944](https://user-images.githubusercontent.com/26581059/182890469-f894ee2e-0e35-4b9a-bce3-fa0b555b9ef5.png)

I had a case where I only received gene symbol from the sequencer and, after converting gene symbol to ENS with Nikos script, I had something like this (see examples of problematic genes with the arrow, duplicated gene symbols):
![image](https://user-images.githubusercontent.com/26581059/182891529-1a675d44-5f2c-48bb-b45a-226e756c03dc.png)

This was fine for besca because we typically work with the symbol column, but MongoDB reads the ensembl column. Therefore there should be some check ensuring that each row is a unique ENS:SYMBOL

I think the general issue is about raising warnings (or errors?) at each import/export step if not compliant with mongoDB

**Comment by hatjek** [comment]
I would suggest just a quick test:
For symbols: These should be mixtures of letters and numbers. They should not be empty, not NA, and not pure nunbers.
For ensembl IDs: They should start with "ENS" and end with numbers.
A warning if this is not the case should be sufficient for the moment.
