### ISSUE TITLE
pbmc_storage dataset

### ISSUE THREAD

**Issue by hatjek** [bedapub/besca#19]
- Remove pbmc_storage dataset and associated functions.
- Replace pbmc_storage dataset by public PBMC dataset uploaded in Zenodo:  https://zenodo.org/communities/besca/

**Comment by Artemis-R** [comment]
- update dataset functions to automatically download the datasets from the zenodo link if not already present to circumvent the issue with not being able to store large quantities of data on GitHub

**Comment by Accio** [comment]
Hi both, I tried Zenodo and it works. Though in the current setting, the solution by @Artemis-R is not feasible because a verification step is needed.

In the standard workflow now, the function is `bc.datasets.pbmc_storage_processed()` is broken, because the file pbmc_storage_processed_downsampled.h5ad is not found. I guess this is related with this issue.
