### ISSUE TITLE
Standard workflow related

### ISSUE THREAD

**Issue by swalpe** [bedapub/besca#20]
The default of the sw is currently 

#read input data
#adata = bc.st.read_matrix(root_path)
adata = bc.datasets.pbmc_storage_raw()#(root_path)

Perhaps it should be 
adata = bc.st.read_matrix(root_path)
#adata = bc.datasets.pbmc_storage_raw()#(root_path)

with some explanation on what the alterantives mean; also for me, bc.datasets. ... didn't work

**Comment by Artemis-R** [comment]
Totally agree. Also thought this when using the standard workflow. 

The bc.datasets currently doesn't work anymore because we had to remove the datasets due to size limitations on files contained in the GitHub repository. We have already decided on how to solve this issue by uploading the .h5ad objects to an alternative data repository and updating the dataset functions to download the files using a link if they are not already present on the users system. Probably we should note this in a separate issue though so that we don't forget to address it.

**Comment by Artemis-R** [comment]
Actually just saw that @hatjek already noted this in an issue (#19).

**Comment by swalpe** [comment]
Change jitter=0.2 from 0.4

**Comment by swalpe** [comment]
also the labels in many plots don't show well when we have many samples. i typically add sns.set_context("paper", font_scale=0.9) somewhere, perhaps we can add this as a param at the start?

**Comment by Artemis-R** [comment]
I like that. In addition we could add some parameters for standardizing plot appearance. I e.g. usually add `plt.rcParams['svg.fonttype'] = 'none'` at the top of all of my notebooks so that generated svgs have editable fonts instead of being displayed as paths. (In my opinion exporting as svg has worked better than pdf for editing figures later in a vector graphic editing program to e.g. adjust font size of axes labels).

**Comment by Artemis-R** [comment]
closed by 6313ce5
