### ISSUE TITLE
Documentation to improve

### ISSUE THREAD

**Issue by ajulienla** [bedapub/besca#6]
See for example pp.fraction_counts

How the specific_file formating should be is not clear.

**Comment by Artemis-R** [comment]
Documentation of installation procedure of besca is missing and needs to be added. Since a couple of packages need to be compiled (e.g. leuvenalg) there are a few installation prerequisites users will have to fulfill. I will do a clean reinstall of my Mac soon and will then test this out and write up the required steps for MacOS. Hopefully this should be the same for other operating systems.

**Comment by ajulienla** [comment]
+ adding infomation about needed git-lfs for dataset information.

**Comment by ajulienla** [comment]
Closed as #12 is clearer and consist of similar discussion.
